# Generated by Django 4.2.7 on 2025-07-26 21:45

import apps.uploads.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.uploads.models.upload_path, verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], max_length=20, verbose_name='file type')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='thumbnail')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('uploader_name', models.CharField(blank=True, max_length=100, verbose_name='uploader name')),
                ('uploader_email', models.EmailField(blank=True, max_length=254, verbose_name='uploader email')),
                ('uploader_phone', models.CharField(blank=True, max_length=20, verbose_name='uploader phone')),
                ('caption', models.TextField(blank=True, verbose_name='caption')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('exif_data', models.JSONField(blank=True, default=dict, verbose_name='EXIF data')),
                ('location_data', models.JSONField(blank=True, default=dict, verbose_name='location data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='approved', max_length=20, verbose_name='status')),
                ('moderation_note', models.TextField(blank=True, verbose_name='moderation note')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='moderated at')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='like count')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='download count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='albums.album', verbose_name='album')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_uploads', to=settings.AUTH_USER_MODEL, verbose_name='moderated by')),
                ('uploader_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='uploader user')),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
                'db_table': 'uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('is_approved', models.BooleanField(default=True, verbose_name='is approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='uploads.uploadcomment', verbose_name='parent comment')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='uploads.upload', verbose_name='upload')),
            ],
            options={
                'verbose_name': 'Upload Comment',
                'verbose_name_plural': 'Upload Comments',
                'db_table': 'upload_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('copyright', 'Copyright Violation'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=20, verbose_name='reason')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='is resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='uploads.upload', verbose_name='upload')),
            ],
            options={
                'verbose_name': 'Upload Report',
                'verbose_name_plural': 'Upload Reports',
                'db_table': 'upload_reports',
                'unique_together': {('upload', 'reporter')},
            },
        ),
        migrations.CreateModel(
            name='UploadLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='uploads.upload', verbose_name='upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Upload Like',
                'verbose_name_plural': 'Upload Likes',
                'db_table': 'upload_likes',
                'unique_together': {('upload', 'user')},
            },
        ),
    ]
