# Generated by Django 4.2.16 on 2026-08-22 17:19

import apps.uploads.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadlike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='upload',
            name='exif_data',
        ),
        migrations.AddField(
            model_name='upload',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='SHA-256 hash'),
        ),
        migrations.AddField(
            model_name='uploadlike',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='session key'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.uploads.models.thumbnail_path, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='uploadlike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_likes', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
